export type DealCategory = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
};

export const DEAL_CATEGORIES: DealCategory[] = [
  {
    id: "electronics",
    label: "Electronics",
    description: "Headphones, TVs, computers, smart home, and accessories.",
    keywords: [
      "laptop",
      "macbook",
      "chromebook",
      "monitor",
      "tv",
      "oled",
      "soundbar",
      "headphone",
      "headset",
      "earbud",
      "earphone",
      "airpods",
      "speaker",
      "bluetooth",
      "router",
      "modem",
      "ssd",
      "nvme",
      "hard drive",
      "ram",
      "memory",
      "keyboard",
      "mouse",
      "webcam",
      "usb",
      "charger",
      "power bank",
      "hdmi",
      "ethernet",
      "smartphone",
      "iphone",
      "android",
      "pixel",
      "galaxy",
      "tablet",
      "ipad",
      "kindle",
      "echo",
      "alexa",
      "ring",
      "smart",
      "camera",
      "projector",
      "gaming",
      "console",
      "playstation",
      "ps5",
      "xbox",
      "switch",
      "gpu",
      "graphics card",
      "smartwatch",
    ],
  },
  {
    id: "clothing",
    label: "Clothing & Shoes",
    description: "Apparel, footwear, and everyday basics.",
    keywords: [
      "shirt",
      "t-shirt",
      "hoodie",
      "jacket",
      "coat",
      "sweater",
      "sweatshirt",
      "sweatpants",
      "pajama",
      "pajamas",
      "jeans",
      "pants",
      "legging",
      "dress",
      "skirt",
      "bra",
      "underwear",
      "sock",
      "socks",
      "shoe",
      "sneaker",
      "boot",
      "sandal",
      "athletic",
      "apparel",
      "clothing",
      "hat",
      "cap",
      "men's",
      "women's",
      "kids",
    ],
  },
  {
    id: "cleaning",
    label: "Cleaning",
    description: "Household cleaners, paper goods, and fresheners.",
    keywords: [
      "detergent",
      "laundry",
      "dish soap",
      "dishwasher",
      "paper towel",
      "toilet paper",
      "trash bag",
      "cleaner",
      "bleach",
      "disinfect",
      "mop",
      "vacuum",
      "air purifier",
      "purifier",
      "humidifier",
      "dehumidifier",
      "broom",
      "swiffer",
      "air freshener",
      "spray",
    ],
  },
  {
    id: "home",
    label: "Home & Kitchen",
    description: "Kitchen, decor, bedding, and storage upgrades.",
    keywords: [
      "kitchen",
      "cookware",
      "pan",
      "pot",
      "knife",
      "cutting board",
      "coffee",
      "espresso",
      "blender",
      "air fryer",
      "slow cooker",
      "pressure cooker",
      "instant pot",
      "bedding",
      "sheet",
      "pillow",
      "blanket",
      "mattress",
      "sofa",
      "chair",
      "lamp",
      "storage",
      "organizer",
      "bath",
      "towel",
      "curtain",
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Health",
    description: "Skincare, grooming, wellness, and personal care.",
    keywords: [
      "skincare",
      "serum",
      "moisturizer",
      "shampoo",
      "conditioner",
      "deodorant",
      "razor",
      "shaver",
      "toothbrush",
      "face wash",
      "lotion",
      "sunscreen",
      "vitamin",
      "supplement",
      "protein",
      "makeup",
      "hair",
      "fragrance",
    ],
  },
  {
    id: "grocery",
    label: "Grocery & Pantry",
    description: "Snacks, coffee, pantry staples, and beverages.",
    keywords: [
      "coffee",
      "tea",
      "snack",
      "chips",
      "cereal",
      "protein bar",
      "protein",
      "granola",
      "kcup",
      "k-cup",
      "sauce",
      "spice",
      "pantry",
      "beverage",
      "energy drink",
      "water",
    ],
  },
  {
    id: "sports",
    label: "Outdoors & Fitness",
    description: "Training gear, outdoors, bikes, and recreation.",
    keywords: [
      "fitness",
      "gym",
      "dumbbell",
      "weight",
      "weights",
      "yoga",
      "yoga mat",
      "resistance band",
      "treadmill",
      "elliptical",
      "bike",
      "cycling",
      "camping",
      "hiking",
      "outdoor",
      "tent",
      "sleeping bag",
      "backpack",
    ],
  },
  {
    id: "toys",
    label: "Toys & Games",
    description: "Games, puzzles, and kid-friendly picks.",
    keywords: [
      "toy",
      "lego",
      "board game",
      "puzzle",
      "nerf",
      "barbie",
      "kids",
      "toddler",
      "playset",
    ],
  },
  {
    id: "office",
    label: "Office & School",
    description: "Desk gear, stationery, and work essentials.",
    keywords: [
      "office",
      "desk",
      "chair",
      "planner",
      "notebook",
      "paper",
      "printer",
      "ink",
      "pen",
      "backpack",
      "calculator",
      "lamp",
    ],
  },
  {
    id: "auto",
    label: "Auto & Tools",
    description: "Car gear, tools, and DIY essentials.",
    keywords: [
      "car",
      "auto",
      "dash cam",
      "jumper",
      "battery",
      "tire",
      "oil",
      "wiper",
      "detail",
      "car charger",
      "tool",
      "drill",
      "screwdriver",
      "socket",
      "wrench",
      "garage",
    ],
  },
  {
    id: "pet",
    label: "Pet Supplies",
    description: "Food, toys, and essentials for pets.",
    keywords: [
      "pet",
      "dog",
      "cat",
      "litter",
      "treat",
      "leash",
      "collar",
      "kibble",
      "dog food",
      "cat food",
      "scratch",
    ],
  },
  {
    id: "other",
    label: "More Deals",
    description: "Everything else we find from Amazon drops.",
    keywords: [],
  },
];

const CATEGORY_INDEX = new Map(
  DEAL_CATEGORIES.map((category) => [category.id, category])
);

export function getDealCategory(title: string, description?: string | null): DealCategory {
  const content = `${title} ${description || ""}`.toLowerCase();
  for (const category of DEAL_CATEGORIES) {
    if (category.id === "other") continue;
    if (category.keywords.some((keyword) => content.includes(keyword))) {
      return category;
    }
  }
  return CATEGORY_INDEX.get("other")!;
}

export function getCategoryById(id: string): DealCategory {
  return CATEGORY_INDEX.get(id) || CATEGORY_INDEX.get("other")!;
}
