export type DealCategory = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
};

export const DEAL_CATEGORIES: DealCategory[] = [
  {
    id: "electronics",
    label: "Electronics",
    description: "Headphones, TVs, computers, smart home, and accessories.",
    keywords: [
      "laptop",
      "desktop",
      "pc",
      "macbook",
      "chromebook",
      "monitor",
      "tv",
      "oled",
      "roku",
      "fire tv",
      "streaming",
      "soundbar",
      "headphone",
      "headset",
      "earbud",
      "earphone",
      "earbuds",
      "airpods",
      "speaker",
      "bluetooth",
      "router",
      "modem",
      "ssd",
      "nvme",
      "hard drive",
      "external drive",
      "ram",
      "memory",
      "motherboard",
      "cpu",
      "keyboard",
      "mouse",
      "webcam",
      "microphone",
      "usb",
      "usb-c",
      "usb c",
      "charger",
      "power bank",
      "power strip",
      "surge protector",
      "hdmi",
      "ethernet",
      "smartphone",
      "iphone",
      "android",
      "pixel",
      "galaxy",
      "tablet",
      "ipad",
      "kindle",
      "echo",
      "alexa",
      "ring",
      "smart",
      "camera",
      "security",
      "projector",
      "gaming",
      "console",
      "playstation",
      "ps5",
      "xbox",
      "nintendo",
      "switch",
      "gpu",
      "graphics card",
      "smartwatch",
      "wearable",
    ],
  },
  {
    id: "clothing",
    label: "Clothing & Shoes",
    description: "Apparel, footwear, and everyday basics.",
    keywords: [
      "shirt",
      "t-shirt",
      "hoodie",
      "jacket",
      "coat",
      "sweater",
      "sweatshirt",
      "sweatpants",
      "pajama",
      "pajamas",
      "jeans",
      "pants",
      "shorts",
      "legging",
      "dress",
      "skirt",
      "bra",
      "underwear",
      "sock",
      "socks",
      "shoe",
      "sneaker",
      "boot",
      "sandal",
      "slipper",
      "loafer",
      "athletic",
      "apparel",
      "clothing",
      "hat",
      "cap",
      "beanie",
      "men's",
      "women's",
      "kids",
    ],
  },
  {
    id: "cleaning",
    label: "Cleaning",
    description: "Household cleaners, paper goods, and fresheners.",
    keywords: [
      "detergent",
      "laundry",
      "dish soap",
      "dishwasher",
      "paper towel",
      "toilet paper",
      "trash bag",
      "trash bags",
      "cleaner",
      "bleach",
      "disinfect",
      "mop",
      "vacuum",
      "robot vacuum",
      "air purifier",
      "purifier",
      "humidifier",
      "dehumidifier",
      "broom",
      "swiffer",
      "air freshener",
      "spray",
    ],
  },
  {
    id: "home",
    label: "Home & Kitchen",
    description: "Kitchen, decor, bedding, and storage upgrades.",
    keywords: [
      "kitchen",
      "cookware",
      "pan",
      "pot",
      "knife",
      "cutting board",
      "coffee",
      "espresso",
      "blender",
      "air fryer",
      "slow cooker",
      "pressure cooker",
      "instant pot",
      "toaster",
      "microwave",
      "kettle",
      "mixing",
      "appliance",
      "bedding",
      "sheet",
      "sheet set",
      "pillow",
      "blanket",
      "comforter",
      "mattress",
      "sofa",
      "chair",
      "lamp",
      "storage",
      "organizer",
      "bath",
      "towel",
      "curtain",
      "rug",
      "furniture",
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Health",
    description: "Skincare, grooming, wellness, and personal care.",
    keywords: [
      "skincare",
      "serum",
      "moisturizer",
      "shampoo",
      "conditioner",
      "deodorant",
      "razor",
      "shaver",
      "toothbrush",
      "face wash",
      "lotion",
      "sunscreen",
      "vitamin",
      "supplement",
      "multivitamin",
      "probiotic",
      "protein",
      "creatine",
      "makeup",
      "hair",
      "fragrance",
      "wellness",
    ],
  },
  {
    id: "grocery",
    label: "Grocery & Pantry",
    description: "Snacks, coffee, pantry staples, and beverages.",
    keywords: [
      "coffee",
      "tea",
      "snack",
      "chips",
      "cereal",
      "protein bar",
      "protein",
      "granola",
      "kcup",
      "k-cup",
      "sauce",
      "spice",
      "condiment",
      "olive oil",
      "pasta",
      "rice",
      "candy",
      "chocolate",
      "pantry",
      "beverage",
      "energy drink",
      "water",
    ],
  },
  {
    id: "sports",
    label: "Outdoors & Fitness",
    description: "Training gear, outdoors, bikes, and recreation.",
    keywords: [
      "fitness",
      "gym",
      "dumbbell",
      "weight",
      "weights",
      "yoga",
      "yoga mat",
      "resistance band",
      "treadmill",
      "elliptical",
      "bike",
      "cycling",
      "camping",
      "hiking",
      "outdoor",
      "tent",
      "sleeping bag",
      "backpack",
      "cooler",
      "kayak",
      "fishing",
    ],
  },
  {
    id: "baby",
    label: "Baby & Kids",
    description: "Diapers, baby gear, and kid essentials.",
    keywords: [
      "baby",
      "infant",
      "toddler",
      "diaper",
      "diapers",
      "wipes",
      "formula",
      "stroller",
      "car seat",
      "crib",
      "bassinet",
      "pacifier",
      "onesie",
      "kids",
    ],
  },
  {
    id: "toys",
    label: "Toys & Games",
    description: "Games, puzzles, and kid-friendly picks.",
    keywords: [
      "toy",
      "lego",
      "board game",
      "puzzle",
      "game",
      "nerf",
      "barbie",
      "kids",
      "toddler",
      "playset",
      "action figure",
    ],
  },
  {
    id: "office",
    label: "Office & School",
    description: "Desk gear, stationery, and work essentials.",
    keywords: [
      "office",
      "desk",
      "chair",
      "planner",
      "notebook",
      "paper",
      "printer",
      "ink",
      "toner",
      "pen",
      "pencil",
      "marker",
      "sticky note",
      "backpack",
      "calculator",
      "lamp",
    ],
  },
  {
    id: "auto",
    label: "Auto & Tools",
    description: "Car gear, tools, and DIY essentials.",
    keywords: [
      "car",
      "auto",
      "dash cam",
      "jumper",
      "battery",
      "battery charger",
      "tire",
      "oil",
      "wiper",
      "detail",
      "car charger",
      "tool",
      "drill",
      "impact",
      "screwdriver",
      "socket",
      "wrench",
      "garage",
    ],
  },
  {
    id: "pet",
    label: "Pet Supplies",
    description: "Food, toys, and essentials for pets.",
    keywords: [
      "pet",
      "dog",
      "cat",
      "litter",
      "treat",
      "leash",
      "collar",
      "kibble",
      "dog food",
      "cat food",
      "pet food",
      "scratch",
    ],
  },
  {
    id: "other",
    label: "More Deals",
    description: "Everything else we find from Amazon drops.",
    keywords: [],
  },
];

const CATEGORY_INDEX = new Map(
  DEAL_CATEGORIES.map((category) => [category.id, category])
);

export function getDealCategory(title: string, description?: string | null): DealCategory {
  const content = `${title} ${description || ""}`.toLowerCase();
  let best: DealCategory | null = null;
  let bestScore = 0;
  for (const category of DEAL_CATEGORIES) {
    if (category.id === "other") continue;
    const score = category.keywords.reduce((total, keyword) => {
      return total + (keywordMatches(content, keyword) ? 1 : 0);
    }, 0);
    if (score > bestScore) {
      bestScore = score;
      best = category;
    }
  }
  return bestScore > 0 && best ? best : CATEGORY_INDEX.get("other")!;
}

export function getCategoryById(id: string): DealCategory {
  return CATEGORY_INDEX.get(id) || CATEGORY_INDEX.get("other")!;
}

function keywordMatches(content: string, keyword: string): boolean {
  if (!keyword) return false;
  if (keyword.includes(" ")) return content.includes(keyword);
  if (keyword.length <= 4) {
    const pattern = new RegExp(`\\b${escapeRegExp(keyword)}\\b`, "i");
    return pattern.test(content);
  }
  return content.includes(keyword);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
