export type DealCategory = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
};

export const DEAL_CATEGORIES: DealCategory[] = [
  {
    id: "electronics",
    label: "Electronics",
    description: "Headphones, TVs, computers, smart home, and accessories.",
    keywords: [
      "laptop",
      "macbook",
      "chromebook",
      "monitor",
      "tv",
      "oled",
      "soundbar",
      "headphone",
      "earbud",
      "speaker",
      "bluetooth",
      "router",
      "ssd",
      "hard drive",
      "keyboard",
      "mouse",
      "webcam",
      "usb",
      "smartphone",
      "iphone",
      "android",
      "tablet",
      "ipad",
      "kindle",
      "echo",
      "alexa",
      "ring",
      "smart",
      "camera",
      "projector",
    ],
  },
  {
    id: "clothing",
    label: "Clothing & Shoes",
    description: "Apparel, footwear, and everyday basics.",
    keywords: [
      "shirt",
      "t-shirt",
      "hoodie",
      "jacket",
      "coat",
      "sweater",
      "jeans",
      "pants",
      "legging",
      "dress",
      "skirt",
      "bra",
      "underwear",
      "sock",
      "shoe",
      "sneaker",
      "boot",
      "sandal",
      "athletic",
      "apparel",
      "clothing",
      "men's",
      "women's",
      "kids",
    ],
  },
  {
    id: "cleaning",
    label: "Cleaning",
    description: "Household cleaners, paper goods, and fresheners.",
    keywords: [
      "detergent",
      "laundry",
      "dish soap",
      "dishwasher",
      "paper towel",
      "toilet paper",
      "trash bag",
      "cleaner",
      "bleach",
      "disinfect",
      "mop",
      "vacuum",
      "broom",
      "swiffer",
      "air freshener",
      "spray",
    ],
  },
  {
    id: "home",
    label: "Home & Kitchen",
    description: "Kitchen, decor, bedding, and storage upgrades.",
    keywords: [
      "kitchen",
      "cookware",
      "pan",
      "pot",
      "knife",
      "cutting board",
      "coffee",
      "espresso",
      "blender",
      "air fryer",
      "bedding",
      "sheet",
      "pillow",
      "blanket",
      "mattress",
      "sofa",
      "chair",
      "lamp",
      "storage",
      "organizer",
      "bath",
      "towel",
    ],
  },
  {
    id: "beauty",
    label: "Beauty & Health",
    description: "Skincare, grooming, wellness, and personal care.",
    keywords: [
      "skincare",
      "serum",
      "moisturizer",
      "shampoo",
      "conditioner",
      "deodorant",
      "razor",
      "shaver",
      "toothbrush",
      "vitamin",
      "supplement",
      "protein",
      "makeup",
      "hair",
      "fragrance",
    ],
  },
  {
    id: "grocery",
    label: "Grocery & Pantry",
    description: "Snacks, coffee, pantry staples, and beverages.",
    keywords: [
      "coffee",
      "tea",
      "snack",
      "chips",
      "cereal",
      "protein bar",
      "granola",
      "sauce",
      "spice",
      "pantry",
      "beverage",
      "energy drink",
      "water",
    ],
  },
  {
    id: "sports",
    label: "Outdoors & Fitness",
    description: "Training gear, outdoors, bikes, and recreation.",
    keywords: [
      "fitness",
      "gym",
      "dumbbell",
      "yoga",
      "treadmill",
      "bike",
      "cycling",
      "camping",
      "hiking",
      "outdoor",
      "tent",
      "sleeping bag",
      "backpack",
    ],
  },
  {
    id: "toys",
    label: "Toys & Games",
    description: "Games, puzzles, and kid-friendly picks.",
    keywords: [
      "toy",
      "lego",
      "board game",
      "puzzle",
      "nerf",
      "barbie",
      "kids",
      "toddler",
      "playset",
    ],
  },
  {
    id: "office",
    label: "Office & School",
    description: "Desk gear, stationery, and work essentials.",
    keywords: [
      "office",
      "desk",
      "chair",
      "planner",
      "notebook",
      "paper",
      "printer",
      "ink",
      "pen",
      "backpack",
      "calculator",
    ],
  },
  {
    id: "auto",
    label: "Auto & Tools",
    description: "Car gear, tools, and DIY essentials.",
    keywords: [
      "car",
      "auto",
      "dash cam",
      "jumper",
      "battery",
      "tool",
      "drill",
      "screwdriver",
      "socket",
      "wrench",
      "garage",
    ],
  },
  {
    id: "pet",
    label: "Pet Supplies",
    description: "Food, toys, and essentials for pets.",
    keywords: [
      "pet",
      "dog",
      "cat",
      "litter",
      "treat",
      "leash",
      "collar",
      "kibble",
      "scratch",
    ],
  },
  {
    id: "other",
    label: "More Deals",
    description: "Everything else we find from Amazon drops.",
    keywords: [],
  },
];

const CATEGORY_INDEX = new Map(
  DEAL_CATEGORIES.map((category) => [category.id, category])
);

export function getDealCategory(title: string, description?: string | null): DealCategory {
  const content = `${title} ${description || ""}`.toLowerCase();
  for (const category of DEAL_CATEGORIES) {
    if (category.id === "other") continue;
    if (category.keywords.some((keyword) => content.includes(keyword))) {
      return category;
    }
  }
  return CATEGORY_INDEX.get("other")!;
}

export function getCategoryById(id: string): DealCategory {
  return CATEGORY_INDEX.get(id) || CATEGORY_INDEX.get("other")!;
}
